name: Lint

on: [push]

jobs:
    run-linters:
        runs-on: ubuntu-latest
        steps:
            - name: Check out Git repository
              uses: actions/checkout@v2

            - name: Set up Node
              uses: actions/setup-node@v1
              with:
                  node-version: 18

            - name: Install dependencies
              run: npm ci

            - name: Run linters
              uses: wearerequired/lint-action@v2
              with:
                    eslint: true
 
